## print("""Section A: Data Structures & Control Structures
1.	Create a list of 5 integers. Perform and print the result of the following operations: append, extend, insert, remove, pop, clear, index, count, sort, and reverse.
2.	Create a tuple that stores 3 student names. Try changing the second name in the tuple. What happens? Explain why.
3.	Create a set of integers with some duplicate values. Print the set and explain the output.
4.	Create a dictionary with the keys: 'name', 'age', and 'city'. Update the age and add a new key 'email'. Print the final dictionary.
5.	 Write a script that checks if a person is eligible to vote (age ≥ 18). Take age as a variable and print the appropriate message.
6.	Given a 'marks' variable, print the grade:
- 90 and above: 'A'
- 75–89: 'B'
- 50–74: 'C'
- Below 50: 'Fail'
7.	Given a number, check if it's positive, and if it is also even. If not positive, print if it's zero or negative.
Section B: Numpy
8.	Create:
- A scalar using np.array(5)
- A 1D array with values 1 to 5
- A 2D array (2x3) with values from 10 to 60 in steps of 10
9.	Generate a 4x4 Numpy array of random integers between 0 and 100 using np.random.randint().
10.	Create a 2D numpy array of shape (3x3). Convert it into a pandas DataFrame and add column names: 'A', 'B', 'C'.
Section C: Exploring Pandas
11.	Create a small DataFrame manually with 10 rows and columns: 'Name', 'Age', 'City', and 'Salary'. Then:
- Use .info(), .describe()
- Select 'Name' and 'City' columns
- Drop 'City' column
- Fill any missing values in 'Salary' column with the mean
- Remove any duplicate rows""")


SECTION A DATA STRUCTURE & CONTROL STRUCTURE

1:Create a list of 5 integers. Perform and print the result of the following operations: append, extend, insert, remove, pop, clear, index, count, sort, and reverse.

In [2]:
numbers = [10, 20, 30, 40, 50]
print("Original List:", numbers)

numbers.append(60)
print("After Append:", numbers)

numbers.extend([70, 80])
print("After Extend:", numbers)

numbers.insert(2, 25)
print("After Insert:", numbers)

numbers.remove(40)
print("After Remove:", numbers)

numbers.pop()
print("After Pop:", numbers)

print("Index of 30:", numbers.index(30))

print("Count of 20:", numbers.count(20))

numbers.sort()
print("After Sort:", numbers)

numbers.reverse()
print("After Reverse:", numbers)

numbers.clear()
print("After Clear:", numbers)

Original List: [10, 20, 30, 40, 50]
After Append: [10, 20, 30, 40, 50, 60]
After Extend: [10, 20, 30, 40, 50, 60, 70, 80]
After Insert: [10, 20, 25, 30, 40, 50, 60, 70, 80]
After Remove: [10, 20, 25, 30, 50, 60, 70, 80]
After Pop: [10, 20, 25, 30, 50, 60, 70]
Index of 30: 3
Count of 20: 1
After Sort: [10, 20, 25, 30, 50, 60, 70]
After Reverse: [70, 60, 50, 30, 25, 20, 10]
After Clear: []


2:Create a tuple that stores 3 student names. Try changing the second name in the tuple. What happens? Explain why.

In [3]:
students = ("Akshay", "Rahul", "Amit")
print("Original Tuple:", students)
try:
    students[1] = "Rohan"
except TypeError as e:
    print("Error:", e)

print("Explanation: Tuples are immutable, so their elements cannot be changed.")

Original Tuple: ('Akshay', 'Rahul', 'Amit')
Error: 'tuple' object does not support item assignment
Explanation: Tuples are immutable, so their elements cannot be changed.


Because tuples are immutable, we cannot modify, add, or remove elements after a tuple is created. Attempting to change an element results in a TypeError.

3:	Create a set of integers with some duplicate values. Print the set and explain the output.

In [5]:
numbers = {1, 2, 2, 3, 4, 4, 5, 5}
print("Set:", numbers)
print("Explanation: Duplicate values are automatically removed in a set.")

Set: {1, 2, 3, 4, 5}
Explanation: Duplicate values are automatically removed in a set.


4: Create a dictionary with the keys: 'name', 'age', and 'city'. Update the age and add a new key 'email'. Print the final dictionary.

In [7]:
student = {
    "name":"Akshay" ,
    "age":21,
    "city":"pune"
        }
student["age"] = 22
student["email"] = "akshay@gmail.com"
print("Update Dictionary:")
print(student)

Update Dictionary:
{'name': 'Akshay', 'age': 22, 'city': 'pune', 'email': 'akshay@gmail.com'}


5: Write a script that checks if a person is eligible to vote (age ≥ 18). Take age as a variable and print the appropriate message.

In [12]:
age = 20
if age >18:
    print("The person is eligible to vote.")
else:
    print("The person is not eligible to vote.")
    

The person is eligible to vote.


6:Given a 'marks' variable, print the grade:
- 90 and above: 'A'
- 75–89: 'B'
- 50–74: 'C'
- Below 50: 'Fail'

In [23]:
marks = 69
if marks>=90:
    print("Grade: A")

elif marks>=75:
    print("Grade: B")

elif marks>=50:
    print("Grade: C")

elif marks>=35:
    print("Grade: F")


Grade: C


7:Given a number, check if it's positive, and if it is also even. If not positive, print if it's zero or negative.

In [24]:
number = 6
if number > 0:
    print("The number is positive.")
    if number % 2 == 0:
        print("The number is even.")
    else:
        print("The number is odd.")
elif number == 0:
    print("The number is zero.")
else:
    print("The number is negative.")

The number is positive.
The number is even.


SECTION B NUMPY

8:Create:
- A scalar using np.array(5)
- A 1D array with values 1 to 5
- A 2D array (2x3) with values from 10 to 60 in steps of 10

In [25]:
import numpy as np
scalar = np.array(5)
print("Scalar:")
print(scalar)


array1 = np.array([1, 2, 3, 4, 5])
print("\n1D Array:")
print(array1)


array2 = np.array([[10, 20, 30],
                   [40, 50, 60]])
print("\n2D Array:")
print(array2)

Scalar:
5

1D Array:
[1 2 3 4 5]

2D Array:
[[10 20 30]
 [40 50 60]]


9:Generate a 4x4 Numpy array of random integers between 0 and 100 using np.random.randint().

In [30]:
import numpy as np
array = np.random.randint(0,101, size=(4,4))
print("4x4 random array:")
print(array)
                     

4x4 random array:
[[90 39 36 15]
 [44 91 65 99]
 [72 64 41 16]
 [73 35 55 43]]


10:Create a 2D numpy array of shape (3x3). Convert it into a pandas DataFrame and add column names: 'A', 'B', 'C'.
Section C: Exploring Pandas

In [41]:
import numpy as np
import pandas as pd
array = np.array([[10,20,30],
                 [40,50,60],
                 [70,80,90]])
df = pd.DataFrame(array, columns=['A', 'B', 'C'])
print(df)

    A   B   C
0  10  20  30
1  40  50  60
2  70  80  90


11:Create a small DataFrame manually with 10 rows and columns: 'Name', 'Age', 'City', and 'Salary'. Then:
- Use .info(), .describe()
- Select 'Name' and 'City' columns
- Drop 'City' column
- Fill any missing values in 'Salary' column with the mean
- Remove any duplicate rows

In [43]:
import pandas as pd
import numpy as np

data = {
    "Name": ["Akshay", "Rahul", "Amit", "Neha", "Pooja",
             "Rohan", "Sneha", "Karan", "Priya", "Om"],
    "Age": [21, 22, 20, 23, 21, 24, 22, 23, 20, 21],
    "City": ["Pune", "Mumbai", "Nashik", "Nagpur", "Pune",
             "Delhi", "Mumbai", "Pune", "Nashik", "Pune"],
    "Salary": [30000, 35000, np.nan, 40000, 38000,
               42000, 36000, np.nan, 39000, 30000]
}

df = pd.DataFrame(data)

print("Original DataFrame:")
print(df)

print("\nDataFrame Info:")
print(df.info())

print("\nDescription:")
print(df.describe())

print("\nName and City Columns:")
print(df[['Name', 'City']])

df = df.drop('City', axis=1)

print("\nAfter Dropping City Column:")
print(df)

df['Salary'] = df['Salary'].fillna(df['Salary'].mean())

print("\nAfter Filling Missing Salary:")
print(df)

df = df.drop_duplicates()

print("\nAfter Removing Duplicate Rows:")
print(df)

Original DataFrame:
     Name  Age    City   Salary
0  Akshay   21    Pune  30000.0
1   Rahul   22  Mumbai  35000.0
2    Amit   20  Nashik      NaN
3    Neha   23  Nagpur  40000.0
4   Pooja   21    Pune  38000.0
5   Rohan   24   Delhi  42000.0
6   Sneha   22  Mumbai  36000.0
7   Karan   23    Pune      NaN
8   Priya   20  Nashik  39000.0
9      Om   21    Pune  30000.0

DataFrame Info:
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 10 entries, 0 to 9
Data columns (total 4 columns):
 #   Column  Non-Null Count  Dtype  
---  ------  --------------  -----  
 0   Name    10 non-null     object 
 1   Age     10 non-null     int64  
 2   City    10 non-null     object 
 3   Salary  8 non-null      float64
dtypes: float64(1), int64(1), object(2)
memory usage: 452.0+ bytes
None

Description:
             Age        Salary
count  10.000000      8.000000
mean   21.700000  36250.000000
std     1.337494   4432.026302
min    20.000000  30000.000000
25%    21.000000  33750.000000
50%    21.500000